---
title: "Lab 6, October 18"
output: 
  tufte::tufte_html:
    css: "lab.css"
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

**Due:** Monday, October 25 at 12pm (noon) on Canvas

**Learning goals:** By the end of this lab, you will be able to

* Fit and interpret multiple regression models with interaction terms
* Perform hypothesis tests, including nested F-tests, on parameters in a multiple regression model

# Setup

**Template file:** [lab_06_template.Rmd](https://sta112-f21.github.io/labs/lab_06_template.Rmd)


**Data**

When a group works together to accomplish a task, a variety of factors may be related to their success. How do diversity and hormone levels impact group performance? The study of group dynamics in the social sciences has often examined these group characteristics, but it is also of interest to explore how they interact. In the paper ["Hormone-Diversity Fit: Collective Testosterone Moderates the Effect of Diversity on Group Performance"](https://journals.sagepub.com/doi/pdf/10.1177/0956797617744282) (Akinola *et al.* 2018, *Psychological Science*), the authors hypothesize that increased group diversity is positively associated with performance when group testosterone levels are low, but increased diversity is negatively associated with performance when testosterone levels are high. Their reasoning is that low-testosterone groups are better at cooperating than high-testosterone groups, so diverse perspectives are beneficial for low-testosterone groups but not for high-testosterone groups.

To investigate their hypothesis, the researchers collected data on 74 groups of MBA students at Columbia University. Each group had 3--6 members, and was tasked with completing a week-long project on maximizing financial performance of a fictional blood-testing laboratory. The data here represents a subset of the data made available by the researchers. Each row in the data represents one group, with the following information:

* *performance*: the final performance of the group in the project
* *size*: the number of group members (between 3 and 6)
* *females*: the number of female group members
* *diversity*: a measure of group diversity that summarizes information on the gender, ethnicity, and country of origin for the group members. Takes on values between 0 and 1 (in this data, the values range from 0.25 to 0.65). Higher diversity scores mean the group is more diverse.
* *testosterone*: the average testosterone levels (in pg/mL) for the group members

The researchers want to look at the relationship between performance, diversity, and testosterone. Because group size and the number of female group members are potential confounding variables, the researchers will also include *size* and *females* as predictors in their model.

# Questions

1. One possible model for the relationship between performance and the group characteristics is the additive model

$\text{performance} = \beta_0 + \beta_1 \text{size} + \beta_2 \text{females} + \beta_3 \text{diversity} + \beta_4 \text{testosterone} + \varepsilon \hspace{1cm} (\text{Equation } 1)$

Fit the regression model in Equation 1. Write down the equation of the fitted model and report the adjusted coefficient of determination ($R^2_{adj}$).

2. What is the *un*adjusted coefficient of determination, $R^2$, for your fitted model in Exercise 1 (what R calls "multiple $R^2$")? Explain why $R^2_{adj} < R^2$.

3. Explain why the model in Equation 1 does not allow the researchers to test the hypothesis that the relationship between group diversity and performance depends on group testosterone levels.

4. To test the hypothesis that the relationship between group diversity and performance depends on group testosterone levels, the researchers add an interaction term:

$\text{performance} = \beta_0 + \beta_1 \text{size} + \beta_2 \text{females} + \beta_3 \text{diversity} + \beta_4 \text{testosterone} + \beta_5 \text{diversity} \cdot \text{testosterone} + \varepsilon \hspace{1cm} (\text{Equation } 2)$

Fit the regression model in Equation 2 using the code below, and write down the equation of the fitted model. Compare $R^2_{adj}$ with your $R^2_{adj}$ value from Exercise 1. How much additional variability in team performance do you explain by adding the interaction term?

```r
performance_lm <- lm(performance ~ size + females + 
                       diversity*testosterone, 
                     data = team_data)
```

:::{.question}
*What's going on here?*

The `lm` function in R works with formulas, like `performance ~ size + females + diversity*testosterone`. The `+` sign means to add another predictor to the model. The `*` means to add both individual predictors and their interaction.
:::

5. Group testosterone varies from about 50 pg/mL for some groups, to about 200 pg/mL for others. Using the equation of the fitted model from Exercise 4, what is the estimated slope for the relationship between diversity and performance when group testosterone is 70 pg/mL (and *size* and *females* are held fixed)? What about when group testosterone is 160 pg/mL?

6. Which type of group do we predict will perform better -- a diverse group with low testosterone, or a homogeneous group with high testosterone? We will make predictions for two new groups: Group A and Group B. Group A has 6 members, two of whom are female, a diversity score of 0.6, and a testosterone level of 70 pg/mL. Group B has 6 members, two of whom are female, a diversity score of 0.3, and a testosterone level of 160 pg/mL. As in simple linear regression, we can create prediction intervals for new groups with these characteristics. Run the code below to create 95% prediction intervals for these two groups:

```r
predict(performance_lm, 
        newdata = data.frame(size = 6, females = 2, 
                             diversity = 0.6, 
                             testosterone = 70), 
        interval="prediction", level = 0.95)

predict(performance_lm, 
        newdata = data.frame(size = 6, females = 2, 
                             diversity = 0.3, 
                             testosterone = 160), 
        interval="prediction", level = 0.95)
```

7. Does the relationship between group diversity and performance depend on group testosterone? We can state this question in terms of hypotheses about a parameter in our model in Equation 2. Write down the null and alternative hypotheses.

8. One method for testing the hypotheses in Exercise 7 is with a nested F-test. Write down the full and reduced models for the nested F-test.

9. To carry out the nested F-test, we fit both the full and reduced models and compare them. If `full_lm` and `reduced_lm` are the fitted models, then `anova(reduced_lm, full_lm)` calculates the F-statistic, degrees of freedom, and the p-value. Carry out the nested F-test for your hypotheses in Exercise 7 and report the p-value. What do you conclude about the hypothesis that the relationship between group diversity and performance depends on testosterone?

10. As you can see in the R output for Exercise 9, for this data the F-statistic comes from an $F_{1, 68}$ distribution. Explain where the numbers 1 and 68 come from.

11. Calculate a confidence interval for the interaction parameter, $\beta_5$, in the model in Equation 2.

12. We haven't yet checked the diagnostics for our multiple regression model. Create a residual plot and a QQ plot for the fitted model from Exercise 4. Do the shape, constant variance, and normality assumptions appear reasonable?

13. Think about the data-generating process for the data. Do the independence and randomness assumptions seem reasonable?

14. Create a studentized residual plot for your fitted  model from Exercise 4. Are there any potential outliers?

15. Since there are a few potential outliers, try removing these outliers and re-fit both the models in Equation 2 and Equation 1. Re-calculate the p-value as in Equation 7, and the confidence interval as in Equation 11. Do your conclusions about the research question change after removing outliers?